<a href="https://colab.research.google.com/github/faspy/monty_python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Arrays**

Dealing with arrays through numpy library

This section covers some basic array methods, such as:

0. np.array( ) `*defined array*`
1. np.arange( ) `*cotinuous array*`
2. np.zeros( )
3. np.ones( )
4. np.linspace( ) `*skipping spaces in array*`
5. np.eye( ) `*identity matrix*`
6. np.random.rand( ) `*random numbers with 0-1 distribution*`
7. np.random.randint( ) `*random numbers with 0-1 distribution*`
8. np.random.randn( ) `*random numbers with standard distribution*`
9. `<array>`.max( ) | `<array>`.argmax( )
10. `<array>`.min( ) | `<array>`.argmin( )
11. `<array>`.reshape( )
12. `<array>`.shape
13. `<array>`.dtype



In [ ]:
my_list = [1,2,3]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(my_list)

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
#Creating an array in a conventional way
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Creating an array in numpy destination functions
np.arange(0,11)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#Skipping numbers in array
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#array of zeros and ones
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#array with evenly space points
#notice that one and two dimensional arrays are differentiated by the numbers of brackets at the beginning
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
#Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#random numbers with 0-1 distribution
np.random.rand(5)

array([0.70499884, 0.15064103, 0.53589463, 0.88214947, 0.30629731])

In [ ]:
np.random.rand(5,5)

array([[0.11224668, 0.54351811, 0.04059516, 0.14794192, 0.97687523],
       [0.37178447, 0.22196751, 0.25177656, 0.59405286, 0.18161683],
       [0.88062366, 0.99648112, 0.9866243 , 0.13982035, 0.64861106],
       [0.01013728, 0.98378099, 0.2471038 , 0.18656626, 0.73242375],
       [0.82864708, 0.06273885, 0.95549163, 0.59862738, 0.90950073]])

In [ ]:
#random numbers with standard distribution
np.random.randn(2)

array([ 1.41351092, -1.0647409 ])

In [ ]:
np.random.randn(4,4)

array([[ 0.08741387, -1.14457405, -1.64921774, -0.57351463],
       [ 0.9313228 ,  0.05428205,  0.53956592,  0.40114468],
       [ 0.0257939 , -0.47924138,  1.31170965,  0.44666471],
       [ 0.38452079,  0.62563689,  0.48916293, -1.9231175 ]])

In [ ]:
#integers with exclusive in the higher
np.random.randint(1,100,10)

array([88, 96, 97, 39, 33, 88, 40, 34, 64,  8])

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(0,50,10)
ranarr

array([48, 34,  5, 15,  0, 47,  0, 31, 43, 37])

In [ ]:
#reshape method - just works with the proper number of elements
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr

array([48, 34,  5, 15,  0, 47,  0, 31, 43, 37])

In [ ]:
ranarr.max()

48

In [ ]:
ranarr.min()

0

In [ ]:
ranarr.argmax()

0

In [ ]:
ranarr.argmin()

4

In [ ]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
#importing an specific method fromm numpy library directly

from numpy.random import randint

In [ ]:
randint(2,10,10)

array([5, 2, 6, 2, 5, 3, 6, 4, 6, 4])

# **Numpy Indexing and Selection**

In [24]:
import numpy as np

arr0 = np.arange(0,11)
arr1 = arr[8]
arr2 = arr[1:5]
arr3 = arr[0:5]
arr4 = arr[:6]
arr5 = arr[5:]

print(arr0)
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10]
8
[1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4 5]
[ 5  6  7  8  9 10]


In [25]:
# Broadcasting values through arrays
slice_of_array = arr0
slice_of_array[0:5] = 100
print('sliced and modified array: ',slice_of_array)

slice_of_array[:] = 99
print('same array modified again: ', slice_of_array)


sliced and modified array:  [100 100 100 100 100   5   6   7   8   9  10]
same array modified again:  [99 99 99 99 99 99 99 99 99 99 99]


In [26]:
#Creating array copies
arr0_copy = arr0.copy()

arr0_copy[:] = 50

print('copied array: ',arr0_copy)
print('original array: ',arr0)

copied array:  [50 50 50 50 50 50 50 50 50 50 50]
original array:  [99 99 99 99 99 99 99 99 99 99 99]


In [29]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
#Grabbing elements from array
arr1_2d = arr_2d[1][1]
print(arr1_2d)

arr2_2d = arr_2d[1,1]
print(arr2_2d)

arr3_2d = arr_2d[:1]
print(arr3_2d)

arr4_2d = arr_2d[:1,2:]
print(arr4_2d)


25
25
[[ 5 10 15]]
[[15]]


In [43]:
#Conditional selection
arr = np.arange(1,11)
print(arr)
print(arr>5)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]


In [48]:
bool_array = arr>5
bool_array

arr1 = arr[bool_array]
arr2 = arr[arr>5]
print(arr1)
print(arr2)

[ 6  7  8  9 10]
[ 6  7  8  9 10]


In [52]:
#Example

arr_2d = np.arange(50).reshape(5,10)
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# **Numpy Operations**

0. Array with Array
1. Array with Scalars
2. Universal Array Functions

In [69]:
import numpy as np

arr = np.arange(0,11)
arr_nzeros = arr[arr>0]

arr_add = arr + arr
arr_sub = arr - arr
arr_mult = arr * arr
arr_div = arr_nzeros / arr_nzeros
arr_exp = arr_nzeros**arr_nzeros

arr_100 = arr-100

print(arr_add)
print(arr_sub)
print(arr_mult)
print(arr_div)
print(arr_exp)
print(arr_100)

[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[          1           4          27         256        3125       46656
      823543    16777216   387420489 10000000000]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]


In [71]:
#Array Functions/methods

#Array square times
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [72]:
#Exponential Array
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [74]:
#Array Maximum
np.max(arr)

10

In [75]:
#Array Sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [77]:
#Array Logs
np.log(arr_nzeros)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])