<a href="https://colab.research.google.com/github/faspy/monty_python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Arrays**

Dealing with arrays through numpy library

This section covers some basic array methods, such as:


1. np.arange( ) `*simple array*`
2. np.zeros( )
3. np.ones( )
4. np.linspace( ) `*skipping spaces in array*`
5. np.eye( ) `*identity matrix*`
6. np.random.rand( ) `*random numbers with 0-1 distribution*`
7. np.random.randint( ) `*random numbers with 0-1 distribution*`
8. np.random.randn( ) `*random numbers with standard distribution*`
9. `<array>`.max( ) | `<array>`.argmax( )
10. `<array>`.min( ) | `<array>`.argmin( )
11. `<array>`.reshape( )
12. `<array>`.shape
13. `<array>`.dtype



In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
#Creating an array in a conventional way
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#Creating an array in numpy destination functions
np.arange(0,11)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
#Skipping numbers in array
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
#array of zeros and ones
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
#array with evenly space points
#notice that one and two dimensional arrays are differentiated by the numbers of brackets at the beginning
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [29]:
#Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
#random numbers with 0-1 distribution
np.random.rand(5)

array([0.70499884, 0.15064103, 0.53589463, 0.88214947, 0.30629731])

In [27]:
np.random.rand(5,5)

array([[0.11224668, 0.54351811, 0.04059516, 0.14794192, 0.97687523],
       [0.37178447, 0.22196751, 0.25177656, 0.59405286, 0.18161683],
       [0.88062366, 0.99648112, 0.9866243 , 0.13982035, 0.64861106],
       [0.01013728, 0.98378099, 0.2471038 , 0.18656626, 0.73242375],
       [0.82864708, 0.06273885, 0.95549163, 0.59862738, 0.90950073]])

In [28]:
#random numbers with standard distribution
np.random.randn(2)

array([ 1.41351092, -1.0647409 ])

In [30]:
np.random.randn(4,4)

array([[ 0.08741387, -1.14457405, -1.64921774, -0.57351463],
       [ 0.9313228 ,  0.05428205,  0.53956592,  0.40114468],
       [ 0.0257939 , -0.47924138,  1.31170965,  0.44666471],
       [ 0.38452079,  0.62563689,  0.48916293, -1.9231175 ]])

In [32]:
#integers with exclusive in the higher
np.random.randint(1,100,10)

array([88, 96, 97, 39, 33, 88, 40, 34, 64,  8])

In [34]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr = np.random.randint(0,50,10)
ranarr

array([48, 34,  5, 15,  0, 47,  0, 31, 43, 37])

In [40]:
#reshape method - just works with the proper number of elements
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr

array([48, 34,  5, 15,  0, 47,  0, 31, 43, 37])

In [44]:
ranarr.max()

48

In [45]:
ranarr.min()

0

In [47]:
ranarr.argmax()

0

In [48]:
ranarr.argmin()

4

In [50]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [51]:
arr.dtype

dtype('int64')

In [52]:
#importing an specific method fromm numpy library directly

from numpy.random import randint

In [54]:
randint(2,10,10)

array([5, 2, 6, 2, 5, 3, 6, 4, 6, 4])

# **Numpy Indexing and Selection**